- Fix the TS error caused by the errant semicolon after an interface declaration. - Version bump for the bugfix. - Version 1.0.2
```
node_modules/@akshat1/js-logger/index.d.ts:11:2 - error TS1036: Statements are not allowed in ambient contexts.
```